accounts:
  - name: alice
    coins: ["100000000uatom", "100000000000000000000aphoton"]
  - name: bob
    coins: ["5000000000000aphoton"]
validator:
  name: alice
  staked: "100000000000000000000aphoton"
faucet:
  name: bob 
  coins: ["10aphoton"]
build:
  binary: "haqqd"
init:
  home: "$HOME/.haqqd"
  app:
    evm-rpc:
      address: "0.0.0.0:8545"     # change the JSON-RPC address and port
      ws-address: "0.0.0.0:8546"  # change the JSON-RPC websocket address and port
genesis:
  chain_id: "haqqd_121713-100"
  app_state:
    staking:
      params:
        bond_denom: "aphoton"
    mint:
      params:
        mint_denom: "aphoton"
    crisis:
      constant_fee:
        denom: "aphoton"
    gov:
      deposit_params:
        min_deposit:
          - amount: "10000000"
            denom: "aphoton"
    evm:
      params:
        evm_denom: "aphoton"
